name: Build

on: push

jobs:

  gcc:
    name: Build (gcc)
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                           pesign gcab gcc-aarch64-linux-gnu
      - name: Build
        working-directory: src
        run: |
          make

  clang:
    name: Build (clang)
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                           pesign gcab binutils-aarch64-linux-gnu
      - name: Build
        working-directory: src
        run: |
          make CC=clang
